[pytest]
# 添加命令行参数
addopts = -s
# 文件搜索路径
testpaths = ./test_cases
# 文件名称
python_files = test*.py
# 类名称
python_classes = Test*
# 方法名称
python_functions = test*
# 注册标记
markers =
    login: 登录测试
    system: 系统测试
    smoke: 冒烟测试